# IP 优选，需要定期修改，最好填写 2 - 4 个
# 域名匹配到 CDN 的 IP 时，会使用优选的 IP 响应请求

include:
  - ./config/hosts.yaml

plugins:
  - tag: blackhole_cloudflare_ipv4
    type: sequence
    args:
      - exec: black_hole 1.1.1.1 # Cloudflare 优选 IPv4
      - exec: ttl 3600-0
      - exec: accept
  - tag: blackhole_cloudflare_ipv6
    type: sequence
    args:
      - exec: black_hole 111::111 # Cloudflare 优选 IPv6
      - exec: ttl 3600-0
      - exec: accept

  - tag: blackhole_gcore_ipv4
    type: sequence
    args:
      - exec: black_hole 2.2.2.2 # G-Core Labs 优选 IPv4
      - exec: ttl 3600-0
      - exec: accept
  - tag: blackhole_gcore_ipv6
    type: sequence
    args:
      - exec: black_hole 222::222 # G-Core Labs 优选 IPv6
      - exec: ttl 3600-0
      - exec: accept

  - tag: blackhole_cloudfront_ipv4
    type: sequence
    args:
      - exec: black_hole 3.3.3.3 # CloudFront 优选 IPv4
      - exec: ttl 3600-0
      - exec: accept
  - tag: blackhole_cloudfront_ipv6
    type: sequence
    args:
      - exec: black_hole 333::333 # CloudFront 优选 IPv6
      - exec: ttl 3600-0
      - exec: accept

  - tag: change_cdn_ip_cloudflare
    type: sequence
    args:
      - matches:
          - qtype 1 # 查询  A 记录
          - has_wanted_ans # 查到 A 记录
          - resp_ip $cloudflare_ipv4 # 查询结果是 Cloudflare 的 IPv4
        exec: jump blackhole_cloudflare_ipv4 # 将结果替换成优选 IPv4
      - matches:
          - qtype 28 # 查询 AAAA 记录
          - has_wanted_ans # 查到 AAAA 记录
          - resp_ip $cloudflare_ipv6 # 查询结果是 Cloudflare 的 IPv6
        exec: jump blackhole_cloudflare_ipv6 # 将结果替换成优选IPv6
      - exec: return

  - tag: change_cdn_ip_gcore
    type: sequence
    args:
      - matches:
          - qtype 1
          - has_wanted_ans
          - resp_ip $gcore_ipv4
        exec: jump blackhole_gcore_ipv4
      - matches:
          - qtype 28
          - has_wanted_ans
          - resp_ip $gcore_ipv6
        exec: jump blackhole_gcore_ipv6
      - exec: return

  - tag: change_cdn_ip_cloudfront
    type: sequence
    args:
      - matches:
          - qtype 1
          - has_wanted_ans
          - resp_ip $cloudfront_ipv4
        exec: jump blackhole_cloudfront_ipv4
      - matches:
          - qtype 28
          - has_wanted_ans
          - resp_ip $cloudfront_ipv6
        exec: jump blackhole_cloudfront_ipv6
      - exec: return

  - tag: change_cdn_ip
    type: sequence
    args:
      - exec: jump change_cdn_ip_cloudflare
      - exec: jump change_cdn_ip_gcore
      - exec: jump change_cdn_ip_cloudfront
      - exec: return
