# 一些域名、IP 表

plugins:
  - tag: geosite_cn # 国内域名
    type: domain_set # 域名集
    args:
      files:
        - ./rule/domain/cn.txt

  - tag: block_site # 需要屏蔽的域名，例如一些广告域名
    type: domain_set
    args:
      files:
        - ./rule/domain/ad.txt # 屏蔽域名列表，https://anti-ad.net/
        # - ./rule/domain/block.txt # 可以自行添加

  # https://www.cloudflare-cn.com/ips/
  - tag: cloudflare_ipv4 # Cloudflare CDN IPv4
    type: ip_set
    args:
      files:
        - ./rule/ip/cloudflare_ipv4.txt
  - tag: cloudflare_ipv6 # Cloudflare CDN IPv6
    type: ip_set
    args:
      files:
        - ./rule/ip/cloudflare_ipv6.txt

  # https://api.gcore.com/cdn/public-ip-list
  - tag: gcore_ipv4 # G-Core Labs CDN IPv4
    type: ip_set
    args:
      files:
        - ./rule/ip/gcore_ipv4.txt
  - tag: gcore_ipv6 # G-Core Labs CDN IPv6
    type: ip_set
    args:
      files:
        - ./rule/ip/gcore_ipv6.txt

  # https://ip-ranges.amazonaws.com/ip-ranges.json
  - tag: cloudfront_ipv4 # CloudFront CDN IPv4
    type: ip_set
    args:
      files:
        - ./rule/ip/cloudfront_ipv4.txt
  - tag: cloudfront_ipv6 # CloudFront CDN IPv6
    type: ip_set
    args:
      files:
        - ./rule/ip/cloudfront_ipv6.txt

  